============================= test session starts ==============================
platform linux -- Python 3.11.3, pytest-8.1.1, pluggy-1.4.0
rootdir: /home/clacina/projects/OurSpending/rest_api
plugins: cov-5.0.0, pretty-1.2.0, anyio-3.7.0
collected 54 items

test/test_db.py ...s.......                                              [ 20%]
test/test_db_resource.py ....                                            [ 27%]
test/test_routes.py ...................sssss..ssssss....F                [ 94%]
test/test_routes.py:330 test_get_processed_transactions - NameError:…
test/test_routes.py ..                                                   [100%]

=================================== FAILURES ===================================
_______________________ test_get_processed_transactions ________________________

    def test_get_processed_transactions():
        bid = random.choice(helpers.get_processed_batch_ids_with_transactions())
        print(f"Calling with batch id {bid}")
>       response = client.get(f"/processed_transactions?batch_id={bid}")

test/test_routes.py:334: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../.pyenv/versions/3.11.3/lib/python3.11/site-packages/starlette/testclient.py:499: in get
    return super().get(
../../../.pyenv/versions/3.11.3/lib/python3.11/site-packages/httpx/_client.py:1054: in get
    return self.request(
../../../.pyenv/versions/3.11.3/lib/python3.11/site-packages/starlette/testclient.py:465: in request
    return super().request(
../../../.pyenv/versions/3.11.3/lib/python3.11/site-packages/httpx/_client.py:827: in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
../../../.pyenv/versions/3.11.3/lib/python3.11/site-packages/httpx/_client.py:914: in send
    response = self._send_handling_auth(
../../../.pyenv/versions/3.11.3/lib/python3.11/site-packages/httpx/_client.py:942: in _send_handling_auth
    response = self._send_handling_redirects(
../../../.pyenv/versions/3.11.3/lib/python3.11/site-packages/httpx/_client.py:979: in _send_handling_redirects
    response = self._send_single_request(request)
../../../.pyenv/versions/3.11.3/lib/python3.11/site-packages/httpx/_client.py:1015: in _send_single_request
    response = transport.handle_request(request)
../../../.pyenv/versions/3.11.3/lib/python3.11/site-packages/starlette/testclient.py:342: in handle_request
    raise exc
../../../.pyenv/versions/3.11.3/lib/python3.11/site-packages/starlette/testclient.py:339: in handle_request
    portal.call(self.app, scope, receive, send)
../../../.pyenv/versions/3.11.3/lib/python3.11/site-packages/anyio/from_thread.py:277: in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
../../../.pyenv/versions/3.11.3/lib/python3.11/concurrent/futures/_base.py:456: in result
    return self.__get_result()
../../../.pyenv/versions/3.11.3/lib/python3.11/concurrent/futures/_base.py:401: in __get_result
    raise self._exception
../../../.pyenv/versions/3.11.3/lib/python3.11/site-packages/anyio/from_thread.py:217: in _call_func
    retval = await retval
../../../.pyenv/versions/3.11.3/lib/python3.11/site-packages/fastapi/applications.py:276: in __call__
    await super().__call__(scope, receive, send)
../../../.pyenv/versions/3.11.3/lib/python3.11/site-packages/starlette/applications.py:122: in __call__
    await self.middleware_stack(scope, receive, send)
../../../.pyenv/versions/3.11.3/lib/python3.11/site-packages/starlette/middleware/errors.py:184: in __call__
    raise exc
../../../.pyenv/versions/3.11.3/lib/python3.11/site-packages/starlette/middleware/errors.py:162: in __call__
    await self.app(scope, receive, _send)
../../../.pyenv/versions/3.11.3/lib/python3.11/site-packages/starlette/middleware/exceptions.py:79: in __call__
    raise exc
../../../.pyenv/versions/3.11.3/lib/python3.11/site-packages/starlette/middleware/exceptions.py:68: in __call__
    await self.app(scope, receive, sender)
../../../.pyenv/versions/3.11.3/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py:21: in __call__
    raise e
../../../.pyenv/versions/3.11.3/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py:18: in __call__
    await self.app(scope, receive, send)
../../../.pyenv/versions/3.11.3/lib/python3.11/site-packages/starlette/routing.py:718: in __call__
    await route.handle(scope, receive, send)
../../../.pyenv/versions/3.11.3/lib/python3.11/site-packages/starlette/routing.py:276: in handle
    await self.app(scope, receive, send)
../../../.pyenv/versions/3.11.3/lib/python3.11/site-packages/starlette/routing.py:66: in app
    response = await func(request)
../../../.pyenv/versions/3.11.3/lib/python3.11/site-packages/fastapi/routing.py:237: in app
    raw_response = await run_endpoint_function(
../../../.pyenv/versions/3.11.3/lib/python3.11/site-packages/fastapi/routing.py:163: in run_endpoint_function
    return await dependant.call(**values)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

batch_id = 634, limit = 100, offset = 0

    @router.get(
        "/processed_transactions",
        response_model=List[models.ProcessedTransactionRecordModel],
        tags=["Processed Transactions"]
    )
    async def get_processed_transactions(batch_id: int, limit: int = 100, offset: int = 0):
        transactions = db_access.get_processed_transaction_records(
            batch_id=batch_id, offset=offset, limit=limit
        )
    
        """
         (142, 1, 1,
             44, 142, 142, 1, datetime.date(2023, 4, 26), 1, ['04/26/2023', '-20.17', '*', '', 'PURCHASE
             AUTHORIZED ON 04/26 ARCO#07027ARCO LAKEWOOD WA P000000272952645 CARD 0094'], 'PURCHASE AUTHORIZED
             ON 04/26 ARCO#07027ARCO LAKEWOOD WA P000000272952645 CARD 0094', Decimal('-20.1700'), 'Wellsfargo
             Checking', 'WLS_CHK', None, None, None, None, None, None, None)
    
    SELECT   processed_transaction_records.id as PID,
             processed_transaction_records.processed_batch_id as BID,
             processed_transaction_records.institution_id,
             processed_transaction_records.template_id, processed_transaction_records.transaction_id,
        """
    
        transaction_list = {}
        if transactions:
            for row in transactions:
                tr = models.ProcessedTransactionRecordModel(
                    id=row[0],
                    processed_batch_id=batch_id,
                    transaction_id=row[4],
                    template_id=row[3],
                    institution_id=row[2],
>                   transaction=parse_transaction_record(row[5:])
                )
E               NameError: name 'parse_transaction_record' is not defined

routes.py:424: NameError
----------------------------- Captured stdout call -----------------------------
Calling with batch id 634
=============================== warnings summary ===============================
test/test_db_resource.py:91
  /home/clacina/projects/OurSpending/rest_api/test/test_db_resource.py:91: PytestCollectionWarning: cannot collect test class 'TestResource' because it has a __init__ constructor (from: test/test_db_resource.py)
    class TestResource(DBResource):

../../../.pyenv/versions/3.11.3/lib/python3.11/site-packages/passlib/utils/__init__.py:854
  /home/clacina/.pyenv/versions/3.11.3/lib/python3.11/site-packages/passlib/utils/__init__.py:854: DeprecationWarning: 'crypt' is deprecated and slated for removal in Python 3.13
    from crypt import crypt as _crypt

../../../.pyenv/versions/3.11.3/lib/python3.11/site-packages/httpx/_client.py:680
  /home/clacina/.pyenv/versions/3.11.3/lib/python3.11/site-packages/httpx/_client.py:680: DeprecationWarning: The 'app' shortcut is now deprecated. Use the explicit style 'transport=WSGITransport(app=...)' instead.
    warnings.warn(message, DeprecationWarning)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

---------- coverage: platform linux, python 3.11.3-final-0 -----------
Name                                                     Stmts   Miss  Cover
----------------------------------------------------------------------------
/home/clacina/projects/OurSpending/common/__init__.py        0      0   100%
/home/clacina/projects/OurSpending/common/db_access.py     587    318    46%
/home/clacina/projects/OurSpending/common/queries.py         4      0   100%
__init__.py                                                  0      0   100%
app.py                                                      45     12    73%
deps.py                                                     29     16    45%
logger.py                                                   37      7    81%
models.py                                                  141     17    88%
reports/__init__.py                                          0      0   100%
reports/db_utils.py                                        170    152    11%
reports/report_processor.py                                 93     78    16%
reports/reports.py                                         126    104    17%
routers/__init__.py                                          0      0   100%
routers/financial.py                                        80     44    45%
routers/templates.py                                        93     50    46%
routers/transactions.py                                    158     95    40%
routes.py                                                  242     97    60%
schemas.py                                                  16      0   100%
template_models.py                                         172     64    63%
test/__init__.py                                             0      0   100%
test/conftest.py                                            10      0   100%
test/helpers.py                                             63     13    79%
test/models.py                                             161      0   100%
test/test_db.py                                             78      4    95%
test/test_db_resource.py                                    68      8    88%
test/test_models.py                                          1      0   100%
test/test_routes.py                                        229     19    92%
user_model.py                                               39     30    23%
utils.py                                                    34     19    44%
----------------------------------------------------------------------------
TOTAL                                                     2676   1147    57%

                                            Summary of Failures                                             
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┓
┃  File                 ┃  Function                         ┃  Function Line  ┃  Error Line  ┃  Error      ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━┩
│  test/test_routes.py  │  test_get_processed_transactions  │  331            │  334         │  NameError  │
└───────────────────────┴───────────────────────────────────┴─────────────────┴──────────────┴─────────────┘
Results (10.25s):
         1 failed
        41 passed
        12 skipped
         3 warnings
